name: Bazel
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/bazel-public/bazel@sha256:65e2c7b5814b000163817ddcfedb16ce3abe4ddd745d683ad399cab14398e4e2
      options: --user root # ref: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GOOGLE_BUCKET: https://storage.googleapis.com/ls-lint-bazel
    steps:
      - run: set -eu
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: bazel test --remote_cache=$GOOGLE_BUCKET --google_default_credentials //...
      - run: bazel build --remote_cache=$GOOGLE_BUCKET --google_default_credentials //...
      - run: bazel run //cmd/ls_lint:ls-lint -- --config ${PWD}/.ls-lint.yml --workdir ${PWD}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: gcr.io/bazel-public/bazel@sha256:65e2c7b5814b000163817ddcfedb16ce3abe4ddd745d683ad399cab14398e4e2
      options: --user root # ref: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user
    env:
      GH_TOKEN: ${{ github.token }}
      STABLE_GIT_TAG: ${{ github.ref_name }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GOOGLE_BUCKET: https://storage.googleapis.com/ls-lint-bazel
    steps:
      - run: set -eu && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: bazel run --remote_cache=$GOOGLE_BUCKET --google_default_credentials //deployments/github:ls_lint_publish
      - run: bazel build --remote_cache=$GOOGLE_BUCKET --google_default_credentials //deployments/npm:ls_lint
      - run: (cd bazel-bin/deployments/npm/ls_lint && NPM_CONFIG_USERCONFIG=${GITHUB_WORKSPACE}/deployments/npm/.npmrc npm publish --no-git-checks) # workaround: https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1667995025343689 # --dry-run --tag beta
